name: Deploy Cloud Function
on:
  push:
    branches: [ main ]
env:
  PROJECT: antony-brd
  FUNCTION_NAME: func_helloworld

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT }}
          service_account_key: ${{ secrets.GCP_SA }}
          export_default_credentials: true

      - name: deploy cloud function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          source_dir: functions
          name: func_helloworld
          runtime: python39
          project_id: ${{env.PROJECT}}
          entry_point: hello_http
          region: europe-west1
          labels: app=myApp1
          description: Sample for my own learning
          service_account_email: github-actions@antony-brd.iam.gserviceaccount.com
          max_instances: 2
          
      - name: print function version and ID
        run: |
         echo "Function ${{ env.FUNCTION_NAME }} version ${{ steps.deploy.outputs.version }} has been deployed with ID ${{ steps.deploy.outputs.id }}"

      - name: test the url
        run: curl "${{ steps.deploy.outputs.url }}"